<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_photoswipe_ad"
 *
 * Auto generated by Extension Builder 2017-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PhotoSwipe Ad',
	'description' => 'This extension adds a google ad after each x items. Warning: Adding ads to a pop-up or lightbox is not allowed by Google AdSense Policies. You are using this extension on your own risk.',
	'category' => 'plugin',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
            'jh_photoswipe' => '0.1.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);